# Generated by Django 6.1.1 on 2026-09-16 16:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='modelovehiculo',
            name='unique_marca_modelo',
        ),
        migrations.RemoveConstraint(
            model_name='producto',
            name='producto_costo_no_negativo',
        ),
        migrations.RemoveConstraint(
            model_name='producto',
            name='producto_precio_minimo_no_menor_costo',
        ),
        migrations.RemoveConstraint(
            model_name='producto',
            name='producto_precio_venta_no_menor_minimo',
        ),
        migrations.RemoveConstraint(
            model_name='producto',
            name='producto_anio_fin_no_menor_inicio',
        ),
        migrations.AddField(
            model_name='categoria',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='marca',
            name='logo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='marca',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='modelovehiculo',
            name='marca',
            field=models.ForeignKey(db_column='marca_id', on_delete=django.db.models.deletion.PROTECT, related_name='modelos', to='catalogo.marca'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, db_column='categoria_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='catalogo.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen_principal',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='modelo',
            field=models.ForeignKey(db_column='modelo_id', on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='catalogo.modelovehiculo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_minimo',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='modelovehiculo',
            constraint=models.UniqueConstraint(fields=('marca', 'nombre'), name='uq_modelo_marca'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('costo__isnull', True), ('costo__gte', 0), _connector='OR'), name='chk_costo_positivo'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('precio_minimo__gte', 0)), name='chk_precio_minimo'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('precio_venta__gte', models.F('precio_minimo'))), name='chk_precio_venta'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('anio_fin__gte', models.F('anio_inicio'))), name='chk_anios_producto'),
        ),
        migrations.AlterModelTable(
            name='categoria',
            table='categorias',
        ),
        migrations.AlterModelTable(
            name='marca',
            table='marcas',
        ),
        migrations.AlterModelTable(
            name='modelovehiculo',
            table='modelos_vehiculo',
        ),
        migrations.AlterModelTable(
            name='producto',
            table='productos',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='marca',
        ),
    ]
