# Generated by Django 6.1.1 on 2026-09-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_remove_modelovehiculo_unique_marca_modelo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen_principal',
            field=models.FileField(max_length=500, upload_to='productos/'),
        ),
    ]
