# Generated by Django 6.1.1 on 2026-09-22 19:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_modelovehiculo_anios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogImageJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filters', models.JSONField(default=dict)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CatalogImageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField()),
                ('filename', models.CharField(max_length=250)),
                ('status', models.CharField(db_index=True, default='pending', max_length=16)),
                ('image', models.FileField(blank=True, max_length=500, upload_to='catalogo_limpio/')),
                ('error', models.CharField(blank=True, max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.producto')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='catalogo.catalogimagejob')),
            ],
        ),
        migrations.AddConstraint(
            model_name='catalogimagejob',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('owner',), name='one_active_image_job_per_user'),
        ),
    ]
