# Generated by Django 6.1.1 on 2026-09-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_catalogimagejob_catalogimageitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogimageitem',
            name='heading',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='catalogimagejob',
            name='with_heading',
            field=models.BooleanField(default=False),
        ),
    ]
