# Generated by Django 6.1.1 on 2026-09-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantilla',
            name='archivo_svg',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='plantilla',
            name='nombre',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AddConstraint(
            model_name='plantilla',
            constraint=models.CheckConstraint(condition=models.Q(('ancho__gt', 0)), name='chk_ancho_plantilla'),
        ),
        migrations.AddConstraint(
            model_name='plantilla',
            constraint=models.CheckConstraint(condition=models.Q(('alto__gt', 0)), name='chk_alto_plantilla'),
        ),
        migrations.AlterModelTable(
            name='plantilla',
            table='plantillas',
        ),
    ]
